// All Airtable Field IDs – mirrored from the original Airtable Block
// Batches table fields
export const F = {
  // Batches
  STATUS:                        'flddHEXJWAkJDwsfu',
  RETENTION_AGENT:               'fldjWFj7bNY6uj8wa',
  CSAT_CASES:                    'fldrCrL5clYz65tUp',
  IN_PROGRESS_CSAT:              'fldeljCqI9y5La2sS',
  CALL_TIME:                     'fldJtKilb5ZEoBLLw',
  AVG_CSAT:                      'fld94qQfOkCrBVQcR',
  EARLIEST_CSAT:                 'fldh7jazvoRxOVlP3',
  LATEST_CSAT:                   'fldvsjRm69YbKGkoZ',
  CUSTOMER_NAME:                 'fldRiJnMhIYZrdxfm',
  VOR_UND_NACHNAME:              'fldTfEsbChOBjnl4o',
  GCID:                          'fldN9kAGOpdDovp8w',
  CALLS_SUCCESSFUL:              'fldKMW0Mbm9CSHzyE',
  CALLS_MISSED:                  'fldvY40lyquSC6WCd',
  PROVISION_BASE:                'fld2cQeqT29vEyURy',
  PROVISION_BONUS:               'fld06GRSJ7zYoQo03',
  TOTAL_PROVISION:               'fldCmZJ2vIworK53a',
  CSAT_II_RATING:                'fld5sXEZ1GHu5y4Fw',
  LOWEST_CSAT_I:                 'fld52OqkBDUQpCmbT',
  CSAT_IMPROVEMENT:              'fldtlxWNha3Bogx13',
  CSAT_II_RATING_STRING:         'fldKVLDPtepWO9Fo6',
  CSAT_II_KOMMENTAR:             'fldWZqeEkqRSsSQet',
  END_DATE:                      'fldyTJ5WVsIqw5RmZ',
  IN_PROGRESS_SUB_STATUS:        'fldlsCz7dxLYQoFME',
  SEND_CSAT_II:                  'fldGzguXxAjNMGO9y',
  BLOCKIERT_ESCALATION_TS:       'fldZvy8dCETxtkaWC',
  BLOCKIERT_TELEFON_TS:          'flddlkTvNy4bn7xcB',
  CSAT_II_RESPONDED_TS:          'fldyDggsVC1La2jVn',
  RETENTION_AGENT_TS:            'fldkvKH8oIlTU9PvO',
  DONE_TIMESTAMP:                'fldOQsN6vPx4h9LXl',
  PRE_CALL_RECHERCHE:            'fldHo8ivDyuUinjlw',
  CALLS_SUCCESSFUL_ENPAL:        'fldq9LHIll46w2uyx',
  SOLUTION_COMMUNICATED:         'fldfw8SGJ1nyv1tXn',
  CSAT_II_SENT_TIMESTAMP:        'fldP4Um3fvNIUQdpg',
  BEARBEITUNGSZEIT_TAGE:         'fldw121zekHQrXtaM',
  CLOSED_CASES:                  'fldXbwoKBKLYbKWsJ',
  RESPONSIBILITY:                'fldd8QO47ITvDRkfZ',

  // CSAT table
  CSAT_RATING:                   'fldz1W5jMPlQj3eC7',
  CSAT_RATING_II:                'fldmRxE4lE3bcESCW',
  CSAT_RESPONSE_TIMESTAMP:       'fldxv3YSqAynNoAWe',
  CSAT_II_DATE:                  'flddMc0aqrWvzoaES',
  CUSTOMER_SATISFACTION:         'fld60FASqnCxhGLXJ',

  // Users table
  USER_COLLABORATOR:             'flddr2AP75CxMakbZ',
  PROVISION_ZIEL:                'fldijuCd05jTIq7W2',
  AVG_BEARBEITUNGSZEIT:          'fldsl58Dm3FMk0iB6',
  PROVISION_GESAMT_SUMME:        'fld4xoDe0jJS9dgmj',
  PROVISION_BASE_SUMME:          'fld1lQruBiht155qt',
  PROVISION_BONUS_SUMME:         'fld8JXtWjL8RiuX7u',
  REQUEST_BATCH:                 'fldFoLCPxobZ5SYoI',
} as const;
